### ISSUE TITLE
Add ability to swallow I/O errors

### ISSUE THREAD

**Issue by dan-blanchard** [pystorm/pystorm#12]
_From @msukmanowsky on October 27, 2015 2:31_

When monitoring streamparse topologies with tools like Sentry, receiving tons of errors like:

```
Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
Error streamparse.storm.component in read_messagestreamparse.ipc
```

Lead to alerting fatigue (we've had 5.9K of these in just one of our production topologies, as @dan-blanchard knows :)). The IPC layer shutting down like this, is usually because of another issue like some other component dying and Storm killing components or rebalancing a topology. In the former case, the actual exception is captured elsewhere already, in the latter, it's a non-error. Either way, the utility of the IPC exception is questionable.

My gut instinct is just swallow these exceptions full stop, but maybe others have use for them. Ideas on how to handle the ability to stop these from being raised?

_Copied from original issue: Parsely/streamparse#198_

**Comment by dan-blanchard** [comment]
I'm going to move this issue over to pystorm, since that's where all the IPC code lives now.  I'll make more comments after that.

**Comment by dan-blanchard** [comment]
With pystorm, this raises a `StormWentAwayError` instead of just exiting.  That makes it simpler for someone to catch it and make an intelligent decision about what they want to do.  

That said, most of the time you want the process to die when the pipe is broken, since you've lost communication with the parent process.  It's not something you can really recover from.

**Comment by msukmanowsky** [comment]
Yeah, so perhaps instead of raising any exception, we just `sys.exit(1)` or pick some exit code we reserve for `StormWentAway`?

**Comment by msukmanowsky** [comment]
And ofc, do a `log.info('Parent Storm process went away, exiting')`

**Comment by dan-blanchard** [comment]
Okay, that seems reasonable to me.  Check out #13.
