### ISSUE TITLE
need_task_ids should default to False

### ISSUE THREAD

**Issue by dan-blanchard** [pystorm/pystorm#29]
We currently default to True for backward compatibility reasons, but I would venture to guess that vast majority of users do not care about the IDs of the tasks that their emitted tuples went to.  Disabling is a nice free speedup, but if we made it disabled by default, we would be cutting out extra work for most users.

**Comment by dan-blanchard** [comment]
@msukmanowsky, @amontalenti, @rduplain Any counter-arguments here?

**Comment by msukmanowsky** [comment]
Sounds reasonable to me. I'd vote for this to mean a major version update though.

**Comment by dan-blanchard** [comment]
Definitely would be a major version update.

**Comment by rduplain** [comment]
+1 to this change. When I first came across task IDs in streamparse, I found them to be non-intuitive until I dug into how Storm does it's task bookkeeping. I would expect users to know what they are doing with task IDs if they use the feature, and that the release docs would mention this change clearly.

**Comment by dan-blanchard** [comment]
Okay, I'm going to open a PR for this and we'll move on to pystorm 3.0 for that.  I'll also pin the streamparse 3.0 release to it, so everybody gets this when they upgrade streamparse.
