### ISSUE TITLE
Support Spout activate/deactivate

### ISSUE THREAD

**Issue by dan-blanchard** [pystorm/pystorm#41]
_From @andrewkcarter on January 23, 2017 21:51_

Storm has recently exposed the activate and deactivate events via the `ShellSpout`. I would like to see these made available in streamparse for storm's next release.

https://github.com/apache/storm/pull/1096

_Copied from original issue: Parsely/streamparse#351_

**Comment by andrewkcarter** [comment]
@dan-blanchard you are quick sir. Thank you.
