### ISSUE TITLE
is there any example to show how to start a storm project?

### ISSUE THREAD

**Issue by howardyan93** [pystorm/pystorm#46]
Hi All, as a newbie of storm, I can not find any example to show me how to start a storm project.
the document just tell me the method to create a spout/bolt.
So I cannot figure out how to submit the codes to storm.
Anyone can help? Best regards.

**Comment by amontalenti** [comment]
Hey there @howardyan93,

The pystorm project is more an infrastructure/library for working with Storm's multi-lang API in Python. To actually make use of Python + Storm projects, check out the "sister project", which is called [streamparse](https://github.com/Parsely/streamparse). It makes use of pystorm under the hood. For an overview of this, you can check out the [streamparse quickstart documentation](http://streamparse.readthedocs.io/en/stable/quickstart.html).

**Comment by howardyan93** [comment]
Thank you for your reply. 
bow
