### ISSUE TITLE
Support Storm's custom serialization support for multi-lang. [msgpack]

### ISSUE THREAD

**Issue by dan-blanchard** [pystorm/pystorm#5]
_From @amontalenti on May 6, 2014 16:30_

A recently [merged pull request 84 on the Storm project][merged] implements custom serialization support for the multi-lang protocol. This means that you can technically register other faster serializers than JSON for Storm's tuple data, e.g. we could use [msgpack][msgpack].

In addition, thanks to Storm's built-in support for serialization hooks with Kyro, we could actually switch Tuple serialization from Kyro's built-in JVM-based serializer to something like msgpack. This would potentially allow us to avoid the encode/decode cost associated with using ShellBolts and ShellSpouts.

It would be great for someone from the community to do a prototype of this using a streamparse project, and prove its viability. Then we could merge the support into the core library, build a support library in Java for the custom serializers, and offer documentation for how to set up Storm to leverage them. This will likely fit in very well with our lein-based Storm project management.

[merged]: https://github.com/apache/incubator-storm/pull/84
[msgpack]: http://msgpack.org/

_Copied from original issue: Parsely/streamparse#8_

**Comment by dan-blanchard** [comment]
_From @jsgilmore on May 11, 2014 8:52_

Hi, good to see someone uses my serialisation pull request. I've already implemented a protocol buffer serialization http://www.google.com/url?q=https://github.com/jsgilmore/protoshell&sa=U&ei=jDlvU4DGKsbx0gX9vYGQDQ&ved=0CAsQFjAA&usg=AFQjCNEo9x4r3QZJPuDSzv4PD-gSz0VNMA that you could also use for improved throughput.

**Comment by dan-blanchard** [comment]
_From @amontalenti on May 15, 2014 16:42_

@jsgilmore Thank you. That's pretty interesting. Looks like you're using this with GoStorm?

**Comment by dan-blanchard** [comment]
_From @amontalenti on May 15, 2014 16:42_

Also here are links to [protoshell](https://github.com/jsgilmore/protoshell) and [gostorm](https://github.com/jsgilmore/gostorm) for reference.

**Comment by dan-blanchard** [comment]
Now that Pyleus is out and has support for msgpack serialization, it seems like we could pretty easily adapt their code for this (since it's Apache licensed, and that should be compatible with BSD).

Here are the relevant links:

- [Java MessagePackSerializer](https://github.com/Yelp/pyleus/blob/develop/topology_builder/src/main/java/com/yelp/pyleus/serializer/MessagePackSerializer.java)
- [serializers Python sub-package](https://github.com/Yelp/pyleus/tree/develop/pyleus/storm/serializers)

**Comment by dan-blanchard** [comment]
_From @amontalenti on December 2, 2014 21:54_

Indeed, this is a good idea. Thanks for the links, @dan-blanchard.

**Comment by dan-blanchard** [comment]
_From @rduplain on September 1, 2015 4:15_

Related to #174.

**Comment by dan-blanchard** [comment]
pystorm/pystorm#1 addresses this.

**Comment by jsgilmore** [comment]
Yes, I implemented the pluggable serialisation for Storm, implemented protoshell as a custom protocol buffer serialiser and then used that as an encoding option in gostorrm, since the JSON serialiser throughput was really low (5000 tuples per second).

**Comment by dan-blanchard** [comment]
@jsgilmore And thanks so much for adding that to Storm.  I'm curious to see how much of a difference using msgpack has on our systems in production.
